"""Единицы измерения, знаки и греческие буквы: как они читаются по-немецки.

Единица узнаётся только сразу после числа: «12 GB» — „zwölf Gigabyte“,
«100 ms» — „hundert Millisekunden“. Род единицы нужен для единицы перед ней:
«1 Sekunde» — „eine Sekunde“, «1 Bit» — „ein Bit“; число единицы — для
формы: «1 Millisekunde», но «2 Millisekunden».
"""

from __future__ import annotations

#: обозначение -> (единственное число, множественное, род)
UNITS: dict[str, tuple[str, str, str]] = {
    "%": ("Prozent", "Prozent", "n"),
    "‰": ("Promille", "Promille", "n"),
    "°C": ("Grad Celsius", "Grad Celsius", "n"),
    "°": ("Grad", "Grad", "n"),
    "kB": ("Kilobyte", "Kilobyte", "n"),
    "KB": ("Kilobyte", "Kilobyte", "n"),
    "KiB": ("Kibibyte", "Kibibyte", "n"),
    "MB": ("Megabyte", "Megabyte", "n"),
    "MiB": ("Mebibyte", "Mebibyte", "n"),
    "GB": ("Gigabyte", "Gigabyte", "n"),
    "GiB": ("Gibibyte", "Gibibyte", "n"),
    "TB": ("Terabyte", "Terabyte", "n"),
    "PB": ("Petabyte", "Petabyte", "n"),
    "Byte": ("Byte", "Byte", "n"),
    "Bytes": ("Byte", "Byte", "n"),
    "bit": ("Bit", "Bit", "n"),
    "Bit": ("Bit", "Bit", "n"),
    "kbit": ("Kilobit", "Kilobit", "n"),
    "Mbit": ("Megabit", "Megabit", "n"),
    "Gbit": ("Gigabit", "Gigabit", "n"),
    "bit/s": ("Bit pro Sekunde", "Bit pro Sekunde", "n"),
    "Bit/s": ("Bit pro Sekunde", "Bit pro Sekunde", "n"),
    "bps": ("Bit pro Sekunde", "Bit pro Sekunde", "n"),
    "kbit/s": ("Kilobit pro Sekunde", "Kilobit pro Sekunde", "n"),
    "Mbit/s": ("Megabit pro Sekunde", "Megabit pro Sekunde", "n"),
    "Gbit/s": ("Gigabit pro Sekunde", "Gigabit pro Sekunde", "n"),
    "kB/s": ("Kilobyte pro Sekunde", "Kilobyte pro Sekunde", "n"),
    "MB/s": ("Megabyte pro Sekunde", "Megabyte pro Sekunde", "n"),
    "GB/s": ("Gigabyte pro Sekunde", "Gigabyte pro Sekunde", "n"),
    "Hz": ("Hertz", "Hertz", "n"),
    "kHz": ("Kilohertz", "Kilohertz", "n"),
    "MHz": ("Megahertz", "Megahertz", "n"),
    "GHz": ("Gigahertz", "Gigahertz", "n"),
    "THz": ("Terahertz", "Terahertz", "n"),
    "ps": ("Pikosekunde", "Pikosekunden", "f"),
    "ns": ("Nanosekunde", "Nanosekunden", "f"),
    "µs": ("Mikrosekunde", "Mikrosekunden", "f"),
    "μs": ("Mikrosekunde", "Mikrosekunden", "f"),
    "ms": ("Millisekunde", "Millisekunden", "f"),
    "s": ("Sekunde", "Sekunden", "f"),
    "min": ("Minute", "Minuten", "f"),
    "h": ("Stunde", "Stunden", "f"),
    "nm": ("Nanometer", "Nanometer", "m"),
    "µm": ("Mikrometer", "Mikrometer", "m"),
    "mm": ("Millimeter", "Millimeter", "m"),
    "cm": ("Zentimeter", "Zentimeter", "m"),
    "m": ("Meter", "Meter", "m"),
    "km": ("Kilometer", "Kilometer", "m"),
    "km/h": ("Kilometer pro Stunde", "Kilometer pro Stunde", "m"),
    "mg": ("Milligramm", "Milligramm", "n"),
    "g": ("Gramm", "Gramm", "n"),
    "kg": ("Kilogramm", "Kilogramm", "n"),
    "mW": ("Milliwatt", "Milliwatt", "n"),
    "W": ("Watt", "Watt", "n"),
    "kW": ("Kilowatt", "Kilowatt", "n"),
    "MW": ("Megawatt", "Megawatt", "n"),
    "Wh": ("Wattstunde", "Wattstunden", "f"),
    "kWh": ("Kilowattstunde", "Kilowattstunden", "f"),
    "MWh": ("Megawattstunde", "Megawattstunden", "f"),
    "mV": ("Millivolt", "Millivolt", "n"),
    "V": ("Volt", "Volt", "n"),
    "kV": ("Kilovolt", "Kilovolt", "n"),
    "mA": ("Milliampere", "Milliampere", "n"),
    "A": ("Ampere", "Ampere", "n"),
    "J": ("Joule", "Joule", "n"),
    "Ω": ("Ohm", "Ohm", "n"),
    "px": ("Pixel", "Pixel", "n"),
    "dpi": ("Punkte pro Zoll", "Punkte pro Zoll", "m"),
    "fps": ("Bild pro Sekunde", "Bilder pro Sekunde", "n"),
    "FLOPS": ("Flops", "Flops", "n"),
    "GFLOPS": ("Gigaflops", "Gigaflops", "n"),
    "TFLOPS": ("Teraflops", "Teraflops", "n"),
    "PFLOPS": ("Petaflops", "Petaflops", "n"),
    "€": ("Euro", "Euro", "m"),
    "EUR": ("Euro", "Euro", "m"),
    "$": ("Dollar", "Dollar", "m"),
    "USD": ("Dollar", "Dollar", "m"),
    "£": ("Pfund", "Pfund", "n"),
}

#: математические и прочие знаки; знак, которого здесь нет, не произносится
SYMBOLS: dict[str, str] = {
    "&": "und", "+": "plus", "=": "gleich", "≠": "ungleich", "<": "kleiner als", ">": "größer als",
    "≤": "kleiner gleich", "≥": "größer gleich", "≈": "ungefähr", "×": "mal", "·": "mal", "÷": "geteilt durch",
    "±": "plus minus", "−": "minus", "→": "Pfeil", "⇒": "daraus folgt", "⇔": "genau dann wenn",
    "↔": "genau dann wenn", "∞": "unendlich", "√": "Wurzel aus", "∑": "Summe", "∫": "Integral",
    "∈": "Element von", "∉": "nicht Element von", "⊂": "Teilmenge von", "⊆": "Teilmenge von",
    "∪": "vereinigt mit", "∩": "geschnitten mit", "∀": "für alle", "∃": "es existiert", "∧": "und",
    "∨": "oder", "¬": "nicht", "⊕": "exklusiv oder", "§": "Paragraf", "§§": "Paragrafen", "©": "Copyright",
    "°": "Grad", "%": "Prozent", "‰": "Promille", "€": "Euro", "$": "Dollar", "£": "Pfund", "@": "at",
    "\\": "Backslash", "_": "Unterstrich", "^": "hoch", "²": "Quadrat", "³": "hoch drei", "¹": "hoch eins",
    "½": "ein halb", "¼": "ein Viertel", "¾": "drei Viertel", "†": "gestorben", "∅": "leere Menge",
    "α": "Alpha", "β": "Beta", "γ": "Gamma", "δ": "Delta", "ε": "Epsilon", "ζ": "Zeta", "η": "Eta",
    "θ": "Theta", "ι": "Iota", "κ": "Kappa", "λ": "Lambda", "μ": "My", "ν": "Ny", "ξ": "Xi", "π": "Pi",
    "ρ": "Rho", "σ": "Sigma", "τ": "Tau", "υ": "Ypsilon", "φ": "Phi", "χ": "Chi", "ψ": "Psi", "ω": "Omega",
    "Γ": "Gamma", "Δ": "Delta", "Θ": "Theta", "Λ": "Lambda", "Π": "Pi", "Σ": "Sigma", "Φ": "Phi",
    "Ψ": "Psi", "Ω": "Omega",
}

#: знаки формул: без формул (настройка «формулы») они не читаются
MATH = set("+=≠<>≤≥≈×·÷±−→⇒⇔↔∞√∑∫∈∉⊂⊆∪∩∀∃∧∨¬⊕^²³¹∅")
