"""Сильные и неправильные глаголы немецкого языка.

Для каждого простого глагола: форма 3-го лица единственного числа настоящего
времени, основа претерита, причастие II и вспомогательный глагол перфекта
(h — haben, s — sein). Глаголы с приставками выводятся из простых:
«verstehen» — из «stehen» (versteht, verstand, verstanden), «an|geben» — из
«geben» (gibt an, gab an, angegeben). Приставочные глаголы, у которых
вспомогательный глагол другой, чем у простого («entstehen» — ist entstanden,
хотя «stehen» — hat gestanden), перечислены отдельно.
"""

from __future__ import annotations

#: инфинитив -> (3 л. ед. ч. наст. вр., претерит 1/3 л. ед. ч., причастие II, вспомогательный)
STRONG: dict[str, tuple[str, str, str, str]] = {
    "backen": ("backt", "backte", "gebacken", "h"),
    "befehlen": ("befiehlt", "befahl", "befohlen", "h"),
    "beginnen": ("beginnt", "begann", "begonnen", "h"),
    "beißen": ("beißt", "biss", "gebissen", "h"),
    "bergen": ("birgt", "barg", "geborgen", "h"),
    "betrügen": ("betrügt", "betrog", "betrogen", "h"),
    "biegen": ("biegt", "bog", "gebogen", "h"),
    "bieten": ("bietet", "bot", "geboten", "h"),
    "binden": ("bindet", "band", "gebunden", "h"),
    "bitten": ("bittet", "bat", "gebeten", "h"),
    "blasen": ("bläst", "blies", "geblasen", "h"),
    "bleiben": ("bleibt", "blieb", "geblieben", "s"),
    "braten": ("brät", "briet", "gebraten", "h"),
    "brechen": ("bricht", "brach", "gebrochen", "h"),
    "brennen": ("brennt", "brannte", "gebrannt", "h"),
    "bringen": ("bringt", "brachte", "gebracht", "h"),
    "denken": ("denkt", "dachte", "gedacht", "h"),
    "dringen": ("dringt", "drang", "gedrungen", "s"),
    "dürfen": ("darf", "durfte", "gedurft", "h"),
    "empfehlen": ("empfiehlt", "empfahl", "empfohlen", "h"),
    "empfangen": ("empfängt", "empfing", "empfangen", "h"),
    "essen": ("isst", "aß", "gegessen", "h"),
    "fahren": ("fährt", "fuhr", "gefahren", "s"),
    "fallen": ("fällt", "fiel", "gefallen", "s"),
    "fangen": ("fängt", "fing", "gefangen", "h"),
    "finden": ("findet", "fand", "gefunden", "h"),
    "fliegen": ("fliegt", "flog", "geflogen", "s"),
    "fliehen": ("flieht", "floh", "geflohen", "s"),
    "fließen": ("fließt", "floss", "geflossen", "s"),
    "fressen": ("frisst", "fraß", "gefressen", "h"),
    "frieren": ("friert", "fror", "gefroren", "h"),
    "geben": ("gibt", "gab", "gegeben", "h"),
    "gehen": ("geht", "ging", "gegangen", "s"),
    "gelingen": ("gelingt", "gelang", "gelungen", "s"),
    "gelten": ("gilt", "galt", "gegolten", "h"),
    "genießen": ("genießt", "genoss", "genossen", "h"),
    "geschehen": ("geschieht", "geschah", "geschehen", "s"),
    "gewinnen": ("gewinnt", "gewann", "gewonnen", "h"),
    "gießen": ("gießt", "goss", "gegossen", "h"),
    "gleichen": ("gleicht", "glich", "geglichen", "h"),
    "gleiten": ("gleitet", "glitt", "geglitten", "s"),
    "graben": ("gräbt", "grub", "gegraben", "h"),
    "greifen": ("greift", "griff", "gegriffen", "h"),
    "haben": ("hat", "hatte", "gehabt", "h"),
    "halten": ("hält", "hielt", "gehalten", "h"),
    "hängen": ("hängt", "hing", "gehangen", "h"),
    "heben": ("hebt", "hob", "gehoben", "h"),
    "heißen": ("heißt", "hieß", "geheißen", "h"),
    "helfen": ("hilft", "half", "geholfen", "h"),
    "kennen": ("kennt", "kannte", "gekannt", "h"),
    "klingen": ("klingt", "klang", "geklungen", "h"),
    "kommen": ("kommt", "kam", "gekommen", "s"),
    "können": ("kann", "konnte", "gekonnt", "h"),
    "kriechen": ("kriecht", "kroch", "gekrochen", "s"),
    "laden": ("lädt", "lud", "geladen", "h"),
    "lassen": ("lässt", "ließ", "gelassen", "h"),
    "laufen": ("läuft", "lief", "gelaufen", "s"),
    "leiden": ("leidet", "litt", "gelitten", "h"),
    "leihen": ("leiht", "lieh", "geliehen", "h"),
    "lesen": ("liest", "las", "gelesen", "h"),
    "liegen": ("liegt", "lag", "gelegen", "h"),
    "lügen": ("lügt", "log", "gelogen", "h"),
    "meiden": ("meidet", "mied", "gemieden", "h"),
    "messen": ("misst", "maß", "gemessen", "h"),
    "mögen": ("mag", "mochte", "gemocht", "h"),
    "müssen": ("muss", "musste", "gemusst", "h"),
    "nehmen": ("nimmt", "nahm", "genommen", "h"),
    "nennen": ("nennt", "nannte", "genannt", "h"),
    "pfeifen": ("pfeift", "pfiff", "gepfiffen", "h"),
    "preisen": ("preist", "pries", "gepriesen", "h"),
    "raten": ("rät", "riet", "geraten", "h"),
    "reiben": ("reibt", "rieb", "gerieben", "h"),
    "reißen": ("reißt", "riss", "gerissen", "h"),
    "reiten": ("reitet", "ritt", "geritten", "s"),
    "rennen": ("rennt", "rannte", "gerannt", "s"),
    "riechen": ("riecht", "roch", "gerochen", "h"),
    "ringen": ("ringt", "rang", "gerungen", "h"),
    "rufen": ("ruft", "rief", "gerufen", "h"),
    "schaffen": ("schafft", "schuf", "geschaffen", "h"),
    "scheiden": ("scheidet", "schied", "geschieden", "h"),
    "scheinen": ("scheint", "schien", "geschienen", "h"),
    "schieben": ("schiebt", "schob", "geschoben", "h"),
    "schießen": ("schießt", "schoss", "geschossen", "h"),
    "schlafen": ("schläft", "schlief", "geschlafen", "h"),
    "schlagen": ("schlägt", "schlug", "geschlagen", "h"),
    "schleichen": ("schleicht", "schlich", "geschlichen", "s"),
    "schließen": ("schließt", "schloss", "geschlossen", "h"),
    "schmelzen": ("schmilzt", "schmolz", "geschmolzen", "s"),
    "schneiden": ("schneidet", "schnitt", "geschnitten", "h"),
    "schreiben": ("schreibt", "schrieb", "geschrieben", "h"),
    "schreien": ("schreit", "schrie", "geschrien", "h"),
    "schreiten": ("schreitet", "schritt", "geschritten", "s"),
    "schweigen": ("schweigt", "schwieg", "geschwiegen", "h"),
    "schwimmen": ("schwimmt", "schwamm", "geschwommen", "s"),
    "schwinden": ("schwindet", "schwand", "geschwunden", "s"),
    "schwören": ("schwört", "schwor", "geschworen", "h"),
    "sehen": ("sieht", "sah", "gesehen", "h"),
    "sein": ("ist", "war", "gewesen", "s"),
    "singen": ("singt", "sang", "gesungen", "h"),
    "sinken": ("sinkt", "sank", "gesunken", "s"),
    "sitzen": ("sitzt", "saß", "gesessen", "h"),
    "sollen": ("soll", "sollte", "gesollt", "h"),
    "spinnen": ("spinnt", "spann", "gesponnen", "h"),
    "sprechen": ("spricht", "sprach", "gesprochen", "h"),
    "springen": ("springt", "sprang", "gesprungen", "s"),
    "stechen": ("sticht", "stach", "gestochen", "h"),
    "stehen": ("steht", "stand", "gestanden", "h"),
    "stehlen": ("stiehlt", "stahl", "gestohlen", "h"),
    "steigen": ("steigt", "stieg", "gestiegen", "s"),
    "sterben": ("stirbt", "starb", "gestorben", "s"),
    "stoßen": ("stößt", "stieß", "gestoßen", "h"),
    "streichen": ("streicht", "strich", "gestrichen", "h"),
    "streiten": ("streitet", "stritt", "gestritten", "h"),
    "tragen": ("trägt", "trug", "getragen", "h"),
    "treffen": ("trifft", "traf", "getroffen", "h"),
    "treiben": ("treibt", "trieb", "getrieben", "h"),
    "treten": ("tritt", "trat", "getreten", "s"),
    "schwingen": ("schwingt", "schwang", "geschwungen", "h"),
    "wägen": ("wägt", "wog", "gewogen", "h"),
    "saugen": ("saugt", "sog", "gesogen", "h"),
    "trinken": ("trinkt", "trank", "getrunken", "h"),
    "trügen": ("trügt", "trog", "getrogen", "h"),
    "tun": ("tut", "tat", "getan", "h"),
    "verderben": ("verdirbt", "verdarb", "verdorben", "h"),
    "vergessen": ("vergisst", "vergaß", "vergessen", "h"),
    "verlieren": ("verliert", "verlor", "verloren", "h"),
    "wachsen": ("wächst", "wuchs", "gewachsen", "s"),
    "waschen": ("wäscht", "wusch", "gewaschen", "h"),
    "weichen": ("weicht", "wich", "gewichen", "s"),
    "weisen": ("weist", "wies", "gewiesen", "h"),
    "werben": ("wirbt", "warb", "geworben", "h"),
    "werden": ("wird", "wurde", "geworden", "s"),
    "werfen": ("wirft", "warf", "geworfen", "h"),
    "wiegen": ("wiegt", "wog", "gewogen", "h"),
    "winden": ("windet", "wand", "gewunden", "h"),
    "wissen": ("weiß", "wusste", "gewusst", "h"),
    "wollen": ("will", "wollte", "gewollt", "h"),
    "ziehen": ("zieht", "zog", "gezogen", "h"),
    "zwingen": ("zwingt", "zwang", "gezwungen", "h"),
}

#: приставочные глаголы, у которых вспомогательный глагол перфекта не как у простого
AUXILIARY: dict[str, str] = {
    "entstehen": "s", "erscheinen": "s", "verschwinden": "s", "zerfallen": "s", "verfallen": "s",
    "bekommen": "h", "gefallen": "h", "erfahren": "h", "befahren": "h", "verlaufen": "s", "entkommen": "s",
    "auftreten": "s", "eintreten": "s", "vertreten": "h", "betreten": "h", "übertreten": "h",
    "übersteigen": "h", "besteigen": "h", "ersteigen": "h", "begehen": "h", "vergehen": "s", "entgehen": "s",
    "umgehen": "h", "übergehen": "h", "eingehen": "s", "ausgehen": "s", "vorgehen": "s", "hervorgehen": "s",
    "zurückgehen": "s", "aufwachsen": "s", "erwachsen": "s", "verlassen": "h", "unterlaufen": "s",
    "folgen": "s", "begegnen": "s", "passieren": "s", "reisen": "s", "wandern": "s", "landen": "s",
    "starten": "s", "wechseln": "h", "sterben": "s", "aufwachen": "s", "einschlafen": "s",
    "werden": "s", "sein": "s", "bleiben": "s", "gelingen": "s", "misslingen": "s", "geschehen": "s",
    "ankommen": "s", "vorkommen": "s", "zurückkehren": "s", "entfliehen": "s", "fortschreiten": "s",
    "abhängen": "h", "erfolgen": "s", "verfahren": "h", "fehlschlagen": "s", "zusammenbrechen": "s",
    "scheitern": "s", "abstürzen": "s", "aufwachsen": "s", "aufstehen": "s", "einschlafen": "s",
}

#: модальные глаголы и самые частые неправильные: полные парадигмы
#: (наст. вр.: ich, du, er, wir, ihr, sie; претерит; конъюнктив II)
PARADIGMS: dict[str, dict[str, tuple[str, ...]]] = {
    "sein": {"pres": ("bin", "bist", "ist", "sind", "seid", "sind"),
             "past": ("war", "warst", "war", "waren", "wart", "waren"),
             "subj": ("wäre", "wärst", "wäre", "wären", "wärt", "wären")},
    "haben": {"pres": ("habe", "hast", "hat", "haben", "habt", "haben"),
              "past": ("hatte", "hattest", "hatte", "hatten", "hattet", "hatten"),
              "subj": ("hätte", "hättest", "hätte", "hätten", "hättet", "hätten")},
    "werden": {"pres": ("werde", "wirst", "wird", "werden", "werdet", "werden"),
               "past": ("wurde", "wurdest", "wurde", "wurden", "wurdet", "wurden"),
               "subj": ("würde", "würdest", "würde", "würden", "würdet", "würden")},
    "können": {"pres": ("kann", "kannst", "kann", "können", "könnt", "können"),
               "past": ("konnte", "konntest", "konnte", "konnten", "konntet", "konnten"),
               "subj": ("könnte", "könntest", "könnte", "könnten", "könntet", "könnten")},
    "müssen": {"pres": ("muss", "musst", "muss", "müssen", "müsst", "müssen"),
               "past": ("musste", "musstest", "musste", "mussten", "musstet", "mussten"),
               "subj": ("müsste", "müsstest", "müsste", "müssten", "müsstet", "müssten")},
    "dürfen": {"pres": ("darf", "darfst", "darf", "dürfen", "dürft", "dürfen"),
               "past": ("durfte", "durftest", "durfte", "durften", "durftet", "durften"),
               "subj": ("dürfte", "dürftest", "dürfte", "dürften", "dürftet", "dürften")},
    "sollen": {"pres": ("soll", "sollst", "soll", "sollen", "sollt", "sollen"),
               "past": ("sollte", "solltest", "sollte", "sollten", "solltet", "sollten"),
               "subj": ("sollte", "solltest", "sollte", "sollten", "solltet", "sollten")},
    "wollen": {"pres": ("will", "willst", "will", "wollen", "wollt", "wollen"),
               "past": ("wollte", "wolltest", "wollte", "wollten", "wolltet", "wollten"),
               "subj": ("wollte", "wolltest", "wollte", "wollten", "wolltet", "wollten")},
    "mögen": {"pres": ("mag", "magst", "mag", "mögen", "mögt", "mögen"),
              "past": ("mochte", "mochtest", "mochte", "mochten", "mochtet", "mochten"),
              "subj": ("möchte", "möchtest", "möchte", "möchten", "möchtet", "möchten")},
    "wissen": {"pres": ("weiß", "weißt", "weiß", "wissen", "wisst", "wissen"),
               "past": ("wusste", "wusstest", "wusste", "wussten", "wusstet", "wussten"),
               "subj": ("wüsste", "wüsstest", "wüsste", "wüssten", "wüsstet", "wüssten")},
    "tun": {"pres": ("tue", "tust", "tut", "tun", "tut", "tun"),
            "past": ("tat", "tatest", "tat", "taten", "tatet", "taten"),
            "subj": ("täte", "tätest", "täte", "täten", "tätet", "täten")},
}

#: неотделяемые приставки: причастие без ge- (verwendet, erklärt)
INSEPARABLE = ("be", "emp", "ent", "er", "ge", "miss", "ver", "zer", "hinter", "über", "unter", "wider", "voll")

#: отделяемые приставки, которые узнаются и без пометки «|» в словаре
SEPARABLE = ("auseinander", "zusammen", "zurück", "heraus", "herein", "hervor", "hinaus", "hinzu", "voran",
             "vorbei", "voraus", "weiter", "wieder", "dar", "fest", "fort", "frei", "her", "hin", "los", "mit",
             "nach", "statt", "vor", "weg", "zu", "ab", "an", "auf", "aus", "bei", "ein", "um", "durch")
